CREATE DATABASE [projektBD] ON  PRIMARY 
( NAME = N'projektBD', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL10_50.SQLEXPRESS\MSSQL\DATA\projektBD.mdf' , SIZE = 3072KB , FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'projektBD_log', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL10_50.SQLEXPRESS\MSSQL\DATA\projektBD_log.ldf' , SIZE = 1024KB , FILEGROWTH = 10%)
GO
ALTER DATABASE [projektBD] SET COMPATIBILITY_LEVEL = 100
GO
ALTER DATABASE [projektBD] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [projektBD] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [projektBD] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [projektBD] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [projektBD] SET ARITHABORT OFF 
GO
ALTER DATABASE [projektBD] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [projektBD] SET AUTO_CREATE_STATISTICS ON 
GO
ALTER DATABASE [projektBD] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [projektBD] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [projektBD] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [projektBD] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [projektBD] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [projektBD] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [projektBD] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [projektBD] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [projektBD] SET  DISABLE_BROKER 
GO
ALTER DATABASE [projektBD] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [projektBD] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [projektBD] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [projektBD] SET  READ_WRITE 
GO
ALTER DATABASE [projektBD] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [projektBD] SET  MULTI_USER 
GO
ALTER DATABASE [projektBD] SET PAGE_VERIFY CHECKSUM  
GO
USE [projektBD]
GO
IF NOT EXISTS (SELECT name FROM sys.filegroups WHERE is_default=1 AND name = N'PRIMARY') ALTER DATABASE [projektBD] MODIFY FILEGROUP [PRIMARY] DEFAULT
GO
